### ISSUE TITLE
Error on empty response body

### ISSUE THREAD

**Issue by stevenvegt** [LuvDaSun/angular-hal#11]
First, thanks for this library. It is simple and straightforward. Just like we needed for our project.

A question:
When sending a PUT to a resource which returns a empty response body I see the 
TypeError: Object.keys called on non-object
Now my workaround is to send back an empty {} object. Do you think empty response bodies can be supported?

**Comment by maennchen** [comment]
The library won't crash anymore if an empty object is supplied.

However, I'd recommend solving the problem like @scottux suggested.
