### ISSUE TITLE
Named embedded links

### ISSUE THREAD

**Issue by brogueady** [LuvDaSun/angular-hal#26]
I cannot see a way to access or follow embedded named links (other than self links).

E.g. in
{
&nbsp;&nbsp;"userId":"D14",
&nbsp;&nbsp;&nbsp;&nbsp;"_embedded" : {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"activeGroup":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "groupId":"50014102",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "_links":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        "self":{"href":"http://localhost.autotrader.co.uk:8301/api/group/50014102"},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"dealers":{"href":"http://localhost.autotrader.co.uk:8301/api/group/50014102/dealers"}
}}}}

How do I access/follow the named link "dealers"?

Thanks
Ade

**Comment by avandecreme** [comment]
`$get('dealers')`

You can test that it exists first with `$has('dealers')`

**Comment by maennchen** [comment]
```js
resource
  .$get('activeGroup')
  .then(function(activeGroup) {
    console.log(activeGroup.$href('dealers'));
    return activeGroup.$get('dealers')
  })
  .then(function(dealers) {
    console.log(dealers);
  });
```
