### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by rkusuma** [LuvDaSun/angular-hal#29]
Hi..
How can i add $http{ cache: true } in angular-hal ?

**Comment by elmerbulthuis** [comment]
What would you like to achieve? Caching should be done via http caching headers and the browser caching system!

**Comment by maennchen** [comment]
Since the Pull Request #31 is merged, you can pass on options to `$http` by supplying the options using `httpConfig`.

Example:
```js
halClient
    .$get(apiUrl, {
        httpConfig: {
            cache: true,
        },
    })
    .then(function(apiRoot) {
        // Do something with it
    });
```
