### ISSUE TITLE
rfc6570 is not on the list of dependencies

### ISSUE THREAD

**Issue by besuhoff** [LuvDaSun/angular-hal#38]
This causes, particularly, the following issue:
`Cannot read property 'UriTemplate' of undefined in angular-hal.js at line 135`

**Comment by maennchen** [comment]
At the current state, angular-hal is to be installed via Bower. Npm is just used to install everything for the unit tests.

If you want it to work via npm, feel free to send a pull request.

**Comment by maennchen** [comment]
Actually someone already is doing a pull request for setting up the package.json. #37

**Comment by maennchen** [comment]
The changes are now made in the package.json. It will be released soon.
