### ISSUE TITLE
How to use on node

### ISSUE THREAD

**Issue by McOmghall** [LuvDaSun/angular-hal#39]
I'm trying to use this to combine this with a node app I'm writing to consume external services, I've tried to `require('angular-hal')` but this doesn't find the module, do I need to `require('node_modules...angular-hal`)` this or have you thought of another way? 

As I see it you just need to add `angular-hal.js` as `main` in your `package.json`.

**Comment by maennchen** [comment]
Since the pull request is merged, I think this issue is closed. Reopen if needed.
