### ISSUE TITLE
Content Type parsing error

### ISSUE THREAD

**Issue by skol-pro** [LuvDaSun/angular-hal#46]
I simply tried using the sample code on the readme (replacing urls of course), but I just get the following error:
`apiRoot.$request is not a function`

Any help would be appreciated. :-/

**Comment by maennchen** [comment]
Could you `console.log` the `apiRoot`?

**Comment by skol-pro** [comment]
Wow, fast answer, was expecting to wait for hours :-)
Sure, looks like I get the common stuff from $http:

`Object {}
    catch: function (a)
    error: function (a)
    finally: function (a)
    success: function (a)
    then: function (b,f,h)
    __proto__: Object`

**Comment by maennchen** [comment]
Which version are you on? `v2.0.0-alpha.4`?

**Comment by skol-pro** [comment]
I edited my last post with the ctrl code.
And I simply took the **angular-hal.min.js** from the git repo.

**Comment by maennchen** [comment]
Ah, I see the error in my README.

Try this:

```js
$http({url: 'http://localhost:8080/api-1.0/'})
  .then(function(apiRoot) {
    $rootScope.apiRoot = apiRoot;
  });

$rootScope.$watch('apiRoot', function(apiRoot){
    if (apiRoot != undefined) {
        $rootScope.dashboards = apiRoot.$request().$get('foo');
    }
});
```

**Comment by skol-pro** [comment]
Yeah, I spotted that too, and tried to assign in then, without really real success :(

```json
{
	"data": {
		"_links": {
			"widgets": {
				"href": "http://localhost:8080/api-1.0/widgets{?page,size,sort}",
				"templated": true
			},
			"dashboards": {
				"href": "http://localhost:8080/api-1.0/dashboards{?page,size,sort}",
				"templated": true
			},
			"profile": {
				"href": "http://localhost:8080/api-1.0/profile"
			}
		}
	},
	"status": 200,
	"config": {
		"method": "GET",
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"url": "http://localhost:8080/api-1.0/",
		"headers": {
			"Accept": "application/hal+json, application/json, text/plain, */*"
		}
	},
	"statusText": "OK"
}
```

**Comment by maennchen** [comment]
What `Content-Type` does your server send with the answer?

**Comment by skol-pro** [comment]
`Content-Type:application/hal+json;charset=UTF-8`

**Comment by skol-pro** [comment]
Looks like $http has been kept untouched.

**Comment by maennchen** [comment]
I think I've implemented this line wrong:
https://github.com/LuvDaSun/angular-hal/blob/master/src/http-interception/resource-http-interceptor.factory.js#L52

**Comment by skol-pro** [comment]
WELL SPOTTED !
Something like this would be better ?
```javascript
if (response.headers('Content-Type').indexOf(CONTENT_TYPE) > -1) { ... }
```

**Comment by maennchen** [comment]
I think it would be good to integrate a library like this one:
https://www.npmjs.com/package/content-type

**Comment by skol-pro** [comment]
Not a bad idea indeed, since it's a pretty lightweight library.

**Comment by maennchen** [comment]
Would you be interested to make a pull request for that?

**Comment by skol-pro** [comment]
You mean, to add the library and refactor angular-hal to work with it ?

**Comment by maennchen** [comment]
Yes, exactly. And maybe also write a test for it.

**Comment by skol-pro** [comment]
Ok why not, you have to know that it will be my first time contributing, but I'm really glad to ! :-)

**Comment by skol-pro** [comment]
So, I've created a simple module + factory, but actually I'm just wondering 2 things:
- No node modules folder, could you describe me how you would install the content-type lib ?
- Should I let you create the minified version or is it on contributors shoulders to do this ? If so, how do you proceed ?
- Still not really used to testing. If you do some, I would appreciate, so that I can check what you did !

I quite simply "duplicated" url-generator module & factory to create that, so, no-brain. I wouldn't be surprised if you tell me it's total bull**** :p

As I said, first time contributing, not used to all this stuff, and I'm really happy to be able to learn & contribute :)
