### ISSUE TITLE
README Dependencies

### ISSUE THREAD

**Issue by maennchen** [LuvDaSun/angular-hal#48]
List all dependencies is README.

**Comment by skol-pro** [comment]
Hope you're making good progress on this. I'm currently wondering how I could use angular-hal without having to install content-type **and/or** how to add content-type lib without using npm nor bower.

**Comment by maennchen** [comment]
I advise you to use bower or npm. Best would be a system like webpack or browserify.

You can however download this file: https://github.com/maennchen/content-type/blob/master/index.js
Then you can include it via a script tag directly in your html. (Before angular-hal)

**Comment by skol-pro** [comment]
Ah right, I see the stuff to make it work

```
if(typeof exports !== 'undefined') {
  exports.format = format
  exports.parse = parse
} else {
  window.contentType = {
    format: format,
    parse: parse,
  };
}
```

Thank you, will take a look back at browserify.

**Comment by skol-pro** [comment]
Regarding README again, looks like there is another modification to make (or something else went wrong on my side).
`$rootScope.foo = apiRoot.$request().$get('foo')` can't really work since it returns:
```
d {}
    $$state: Object
    error: function (a)
    success: function (a)
```
And doing this:
```
apiRoot.$request().$get('foo').success(function() {
    // arguments: [undefined, undefined, undefined, Object]
});
```
And returned object at arguments[3]:
```
Object
    data: null
    headers: Object
    method: "GET"
    paramSerializer: function (a)
    transformRequest: Array[1]
    transformResponse: Array[1]
    url: "http://localhost:8080/api-1.0/foo"
```

**Comment by maennchen** [comment]
@skol-pro: That doesn't belong to this issue. If the problem persists, open a new one.

**Comment by skol-pro** [comment]
@maennchen Ok thank you. I switched to the latest stable 1.x version.
