### ISSUE TITLE
Merge is not a function

### ISSUE THREAD

**Issue by skol-pro** [LuvDaSun/angular-hal#49]
I got the following error:
`TypeError: merge is not a function`
At line `661` from angular-hal.js.

**Comment by maennchen** [comment]
Can you please enable the sourcemaps?

**Comment by maennchen** [comment]
Which angular version are you running?

**Comment by skol-pro** [comment]
Angular v1.2.29.

**Comment by skol-pro** [comment]
Ok I see that angular.merge wasn't existing in 1.2.x.

**Comment by maennchen** [comment]
I'll adjust the dependencies...
