### ISSUE TITLE
Using $httpBackend for unit test cases

### ISSUE THREAD

**Issue by prakharjaiswal** [LuvDaSun/angular-hal#50]
Now that angular-hal uses http-interceptor to transform response, is there a way to make $httpBackend request handler work in accordance?
Here's a sample snippet that mocks backend:
```
myRequestHandler = $httpBackend.whenGET('some/url').respond(200, '');

beforeEach(function() {
				jasmine.getJSONFixtures().fixturesPath = 'base/path/to/my/mockresponses';
				myRequestHandler.respond(
					$transformResponseToResource({data: getJSONFixture('mymockdata.json'), config: {url: 'some/url'}})
				);
			});
```

The problem with this code is **myRequestHandler.respond** creates it own **XHR response wrapper** (response status, headers, config etc) around the Resource created by **$transformResponseToResource** function, which is unexpected to the source code (it expects raw Resource object on resolving the **$http** call promise as **ResourceHttpInterceptor** transforms the response into a HAL Resource Object)

Thanks in advance :+1:

**Comment by maennchen** [comment]
There's two ways to achieve the behaviour you want.
1) [Specify a `Content-Type` in the mocked response.](https://github.com/LuvDaSun/angular-hal/blob/master/test/content-type.spec.js#L23)
2) [Use the `setForceJSONResource` Option.](https://github.com/LuvDaSun/angular-hal/blob/master/test/integration/attribute-names.spec.js#L8)

**Comment by prakharjaiswal** [comment]
Thanks, it answers the problem.
