### ISSUE TITLE
import problems

### ISSUE THREAD

**Issue by grofzero** [LuvDaSun/angular-hal#55]
Hi,

I tried to install the new ES6 module with jspm, but I had some problems with it. The npm version is not the same as the github version and it contains a require statement in the http-interception.js, so it breaks the code, but I didn't have luck with the github version either. In the index.js it tries to load the './http-interception' but it doesn't load the index.js in the http-interception folder instead it tries to load the http-interception.js file which soesn't exist. Could you please fix these problems, or tell me if I'm doing something wrong?

Thank you

**Comment by maennchen** [comment]
I was only using it with Babel until now. (With webpack & browserify)

Babel replaces all import / export statements with require / module.exports.
It seem as those two are not alike (For example not loading a index.js automatically)

**Comment by maennchen** [comment]
A solution to this problem could be to run the test multiple times. Once for every environement.

Environements:
 * Jspm
 * Webpack
 * Browserify

Would you be able to provide a PR?

**Comment by grofzero** [comment]
Of course, as soon as I can

**Comment by maennchen** [comment]
I already had the time to build a solution. I'll provide a PR in a few minutes. I'd be happy if you could test it.

**Comment by grofzero** [comment]
Great, it seems to be working, thank you very much:) Could you publish it to npm?

**Comment by maennchen** [comment]
It's published. It may take a few minutes to refresh all npm etc. caches.

**Comment by grofzero** [comment]
Thank you very much, but I still cannot see the 2.1.4 version in npm. Could you check it please?

**Comment by maennchen** [comment]
@elmerbulthuis: The npm deployment is failing again on travis. Could you check and deploy 2.1.4?

**Comment by maennchen** [comment]
@grofzero: Npm still doesn't find `v.2.1.4`. But you can use the newer `v2.1.5`.
