### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by Ceany** [LuvDaSun/angular-hal#59]
I have a question about angular 2 support. 

Does angular-hal easily work with angular 2 or do I have to wait for a new release when angular 2 is final?

This question is regarding a technology research so a try and error is not possible for me.

Thanks in advance

**Comment by maennchen** [comment]
Angular 2 has some fundamental changes. This library heavily relies on the angular 1 `$http` service which is completely different from the angular 2 http service.

I'm going to port the library to angular 2 at some point, but currently there is no support and I don't have the time to implement it.
