### ISSUE TITLE
Readonly fields

### ISSUE THREAD

**Issue by mivano** [LuvDaSun/angular-hal#6]
Hi, 

Trying to use your excellent HAL implementation for Angular. Works fine until I assign the resource object to a scope variable and bind that variable to input elements. They become completly uneditable. At first I thought it was some promise issue (as mentioned here http://stackoverflow.com/questions/16883239/angularjs-ngmodel-field-is-readonly-when-bound-to-q-promise), but there is no promise involved yet and I could not even directly set the field to some other value. Some more diving into the code itself lead me to this code (line 70)

```javascript
      Object.keys(data)
                .filter(function (key) {
                    return !~['_', '$'].indexOf(key[0]);
                })
                .forEach(function (key) {
                    Object.defineProperty(this, key, {
                        configurable: false,
                        enumerable: true,
                        writable:true,   // Added line
                        value: data[key]
                    });
                }, this);
```

I added the _writable: true_ so I can actually change the contents of the fields. It fixes the issue for me, but I might be doing something incorrect here. So what should be the best way to model bind a single item to a form? I could not find an example in your demo project.

Thanks for the library btw!

regards Michiel

**Comment by avandecreme** [comment]
Same problem here.
I would rather not have to make any copy.

**Comment by landerton** [comment]
+1

**Comment by chadkouse** [comment]
:+1:

**Comment by igler** [comment]
+1

**Comment by JR-Utily** [comment]
+1

I have the same kind of problem, and as I want to edit a list of resources and not just one, maintaining a kind of dictionary of (original, working copy) would be troublesome, a lot of thing may happen in the working copy.

With @jbigman solution, we do lost the specific behaviour ($get, $has, etc..) of the resource, so this is not a good workaround for my use case.

This issue is more than one year old. Wouldn't it be possible to make a PR on @mivano solution ?

**Comment by maennchen** [comment]
A resource should not be writable. If you really need to write into a resource, please make a copy of it.

If someone wants to write a pull request for a copy utility method, that'd be great.
