### ISSUE TITLE
PUT a Resource with different links

### ISSUE THREAD

**Issue by francescobragagna** [LuvDaSun/angular-hal#65]
Hi,

I would ask some clarification about library usage best practice in resource and _links update.

I have a resource coming from server like this:

```
{
   "attribute": "oldValue",
   "_links": { 
          "self": "...",
          "related": "{"href": "/resoucesClassB/2" }",
          "another": "{"href": "/pinuts/3"}"
    } 
}
```

I think it's correct have a resource "related" directly in the link, is it?  ("/resourceClassB/2" it's the url to a specific resource)

I would like to update this resource on the server, and change both related resource (change a relationship) and the attribute. 
Suppose the server does not support PATCH, so I need to use PUT.

In a case like this, when I PUT a resource, should I add all its links? (or it's a wrong practice in your point of view?)

Because Hal resource as implemented are immutable, I can't change their values, so I need to do a copy.   Because I need to change also the links, i need to add them to the copy.
(maybe I'm wrong, please help me in case i'm going in the wrong way)

```
var resource = ...;
var relatedResourceB3 = ....;
var selfB3= relatedResourceB3.$href('self');    //  e.g. "/resourceClassB/3"

var resourceCopy = angular.copy(resource);
resourceCopy.attribute = "new value";
resourceCopy._links = { "related": {"href" : selfB3}};

resource.$request().$put('self', null, resourceCopy); 
```

How can I clone a resource, with all its link, to be able to change them? (in this case "another" link is missing), and which is the correct way to change them?
Can I build a "new resource" (not immutable) starting from an existing resource, as a mutable clone?

```
var mutableClone = resource.$mutableClone();
mutableClone.attribute = "new value";
mutableClone.$put();   //with no parameter it could put on self.
```

**Comment by maennchen** [comment]
Hi @francescobragagna,

This is a good question, which I can't really answer.

If you use a `PUT` request, you should always send all the whole resource.

How the whole request should look like I can't answer. I had the same problem with JSON Patches and still don't know how to solve them.

I think this is something that should be clarified by https://github.com/mikekelly/hal_specification

**Comment by maennchen** [comment]
Also if I say `If you use a PUT request, you should always send all the whole resource.`, that doesn't mean that the links have to belong to the resource. But then the question is how to Link them? Link Headers?

**Comment by francescobragagna** [comment]
"I think this is something that should be clarified by https://github.com/mikekelly/hal_specification"
I've already asked similar question here:
https://github.com/mikekelly/hal_specification/issues/5
and
https://groups.google.com/forum/#!topic/hal-discuss/r6T_gTCSBDk

I was expecting more 'common behaviours' on resource update. Because when I need to browse entities there are no problem. 

The problem starts when you need to unlink, link multiple, link existing beween them, and so on, which are in my point of view  common operation on an application with many resources with relationships N:M, 1:N, ... to be maintained.

And in my point of view this problem is related to the meaning of "self" link in an embedded resource.

**Comment by francescobragagna** [comment]
In the google groups I think I've read most of the post (about 400) and somethimes the discussions are going into investigation of self meaning, and resource update. But Mike many times answers it's not a matter of HAL specification define how to update resources. 
I think is partially correct, but partially not.

I've investigated also usage of some of the `[public APIS ](https://github.com/mikekelly/hal_specification/wiki/APIs)`listed in the Mike's github: most of them doesn't update resource, or simply delete/build again them. It's still not clear to me

**Comment by maennchen** [comment]
Since the HAL specification does not specify anything for this matter, I don't think that we'll implement any opinionated solution in this library. Please create a new issue for either an implementation as soon as the specification has a solution or a way for the user to extend the library with opinionated solutions.
