### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by mivano** [LuvDaSun/angular-hal#7]
Hi,

Can you add a license to your project? Would love to use it in our project, but we need to have a license for the components we us so we are covered. I cannot find any now in your repository.

thanks!

**Comment by bdosorio** [comment]
Which form of the BSD licence?

I agree having an explicit licence file would help.

**Comment by elmerbulthuis** [comment]
I just added the WTFPL license in https://github.com/LuvDaSun/angular-hal/commit/cc2af8c09439b7e6b2f0dd0e55ceab67196d7450
